# docker-compose.yml
version: '3.8'
services:

  app:
    build: .
    container_name: newspaper
    ports:
      - "8080:8080"
    # volumes:
    #   - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/news.db