# docker-compose.yml
version: '3.8'
services:

  app:
    build: .
    container_name: news_app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/editions.db