# docker-compose.yml
version: '3.8'
services:

  app:
    build: .
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/mydatabase.db