# docker-compose.deploy.yml
version: '3.8'
services:
  app:
    build: .
    image: "${DOCKER_HUB_USERNAME}/newspaper_app"
    container_name: newspaper
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///app/data/news.db